name: Build and release
on: push
jobs:
  build_and_publish_x64:
    name: Build and publish x86-64
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - run: sudo apt install -y musl-tools
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup target add x86_64-unknown-linux-musl
      - run: cargo build --release --target x86_64-unknown-linux-musl
      - run: cp target/release/recipe_printer recipe_printer_x86-64
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build_x86-64
          path: recipe_printer_*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: recipe_printer_x86-64
  build_and_publish_aarch64:
    name: Build and publish aarch64
    runs-on: ubuntu-24.04-arm
    permissions: 
      contents: write
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools # provides musl-gcc
          version: 1.0
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - run: cp target/release/recipe_printer recipe_printer_aarch64
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build_aarch64
          path: recipe_printer_aarch64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: recipe_printer_aarch64